
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Workspace\expenses_splitter_GUI\Tkinter-Designer\output\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)  


window = Tk()

window.geometry("789x294")
window.configure(bg = "#D1EDF9")


page1 = Canvas(
    window,
    bg = "#D1EDF9",
    height = 294,
    width = 789,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

page1.place(x = 0, y = 0)
page1.create_text(
    167.0,
    125.0,
    anchor="nw",
    text="How many participants?",
    fill="#000000",
    font=("AnonymousPro Regular", 14 * -1)
)

page1.create_text(
    251.0,
    38.0,
    anchor="nw",
    text="Expenses Calculator",
    fill="#000000",
    font=("AnonymousPro Regular", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = page1.create_image(
    390.5,
    134.0,
    image=entry_image_1
)
entry_1 = Entry(
    page1,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=359.0,
    y=121.0,
    width=63.0,
    height=24.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
print(button_image_1)
button_1 = Button(
    page1,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=351.0,
    y=199.0,
    width=80.0,
    height=39.0
)


page2 = Canvas(
    window,
    bg = "#D1EDF9",
    height = 687,
    width = 789,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge",
)

page2.place(x = 0, y = 0)
page2.create_text(
    251.0,
    38.0,
    anchor="nw",
    text="Expenses Calculator",
    fill="#000000",
    font=("AnonymousPro Regular", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = page2.create_image(
    233.5,
    284.5,
    image=entry_image_2
)
entry_2 = Text(
    page2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=24.0,
    y=82.0,
    width=419.0,
    height=403.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = page2.create_image(
    610.5,
    284.0,
    image=entry_image_3
)
entry_3 = Text(
    page2,
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=462.0,
    y=81.0,
    width=297.0,
    height=404.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    page2,
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=285.0,
    y=565.0,
    width=109.0,
    height=44.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    page2,
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=407.0,
    y=565.0,
    width=109.0,
    height=44.0
)

# page1.tkraise() 

# window.resizable(False, False)
window.mainloop()
